language: python
python:
  - "3.5"
cache: pip
install:
  - pip install pillow pyqrcode pypng pyinstaller bottle pycryptodome simple-crypt PySocks requests
script: 
  - pyinstaller --uac-admin --onefile --noconsole --log-level=INFO wallet.py --icon=graphics\icon.ico
  - pyinstaller --uac-admin --onefile --log-level=INFO node.py --icon=graphics\icon.ico
  - pyinstaller --uac-admin --onefile --log-level=INFO miner.py --icon=graphics\icon.ico
notifications:
  slack: cryptobismuth:Mtd8QY1ElBCfM7ijzsyCE7HU
  email: false

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL